FROM grafana/grafana

ADD src/main/grafana/datasource.yaml /etc/grafana/provisioning/datasources
ADD src/main/grafana/dashboard.yaml /etc/grafana/provisioning/dashboards
ADD src/main/grafana/betcapture-scrape-dashboard.json /etc/grafana/betcapture/betcapture-scrape-dashboard.json
ADD src/main/grafana/betcapture-open-bet-dashboard.json /etc/grafana/betcapture/betcapture-open-bet-dashboard.json
